root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/traily-backend ./cmd/main.go"
bin = "./tmp/traily-backend"
include_ext = ["go"]
exclude_dir = ["tmp", "bin", "vendor"]
delay = 200

[log]
time = false

[misc]
clean_on_exit = true
